name: Micropub client CI

on:
  push:
    paths:
      - 'micropub-client/**'

defaults:
  run:
    working-directory: micropub-client

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        # TODO: I hate leaking ops stuff here but I'll have to figure it out later.
        script: ./scripts/update.sh koddsson/micropub-client
