name: Micropub client CI

on:
  push:
    paths:
      - 'micropub-client/**'
      - '.github/workflows/micropub-client.yml'

defaults:
  run:
    working-directory: micropub-client

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        # TODO: I hate leaking ops stuff here but I'll have to figure it out later.
        script: ./scripts/update.sh koddsson/micropub-client
    - uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#github'
      if: always()
